// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TheaterLaakAPi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Bestelling", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("reference")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Bestelling");
                });

            modelBuilder.Entity("Betaling", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("reference")
                        .HasColumnType("TEXT");

                    b.Property<bool>("succes")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Betaling");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroepId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroepId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.ArtiestGroep", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "GroepId");

                    b.HasIndex("GroepId");

                    b.ToTable("ArtiestGroeps");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Groep", b =>
                {
                    b.Property<int>("GroepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtiestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BandWebsite")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroepNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoLink")
                        .HasColumnType("TEXT");

                    b.HasKey("GroepId");

                    b.HasIndex("ArtiestId");

                    b.ToTable("Groepen");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Rang", b =>
                {
                    b.Property<int>("RangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capiciteit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RangNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZaalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RangId");

                    b.HasIndex("ZaalId");

                    b.ToTable("Rangen");

                    b.HasData(
                        new
                        {
                            RangId = 1,
                            Capiciteit = 0,
                            RangNr = 1,
                            ZaalId = 1
                        },
                        new
                        {
                            RangId = 2,
                            Capiciteit = 0,
                            RangNr = 2,
                            ZaalId = 1
                        },
                        new
                        {
                            RangId = 3,
                            Capiciteit = 0,
                            RangNr = 3,
                            ZaalId = 1
                        },
                        new
                        {
                            RangId = 4,
                            Capiciteit = 0,
                            RangNr = 1,
                            ZaalId = 2
                        },
                        new
                        {
                            RangId = 5,
                            Capiciteit = 0,
                            RangNr = 2,
                            ZaalId = 2
                        });
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Reservering", b =>
                {
                    b.Property<int>("ReserveringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReserveringsDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoorstellingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("isBetaald")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReserveringId");

                    b.HasIndex("ApplicationUserId1");

                    b.HasIndex("StoelId");

                    b.HasIndex("VoorstellingId");

                    b.ToTable("Reserveringen");

                    b.HasData(
                        new
                        {
                            ReserveringId = 1,
                            ApplicationUserId = 1,
                            ReserveringsDatum = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoelId = 1,
                            VoorstellingId = 1,
                            isBetaald = 0
                        },
                        new
                        {
                            ReserveringId = 2,
                            ApplicationUserId = 2,
                            ReserveringsDatum = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoelId = 2,
                            VoorstellingId = 1,
                            isBetaald = 0
                        },
                        new
                        {
                            ReserveringId = 3,
                            ApplicationUserId = 3,
                            ReserveringsDatum = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoelId = 3,
                            VoorstellingId = 1,
                            isBetaald = 1
                        },
                        new
                        {
                            ReserveringId = 4,
                            ApplicationUserId = 4,
                            ReserveringsDatum = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoelId = 1,
                            VoorstellingId = 2,
                            isBetaald = 0
                        },
                        new
                        {
                            ReserveringId = 5,
                            ApplicationUserId = 5,
                            ReserveringsDatum = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoelId = 2,
                            VoorstellingId = 2,
                            isBetaald = 1
                        });
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Stoel", b =>
                {
                    b.Property<int>("StoelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RangId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoelNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("isInvalide")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoelId");

                    b.HasIndex("RangId");

                    b.ToTable("Stoelen");

                    b.HasData(
                        new
                        {
                            StoelId = 1,
                            RangId = 1,
                            StoelNr = 1,
                            isInvalide = 0
                        },
                        new
                        {
                            StoelId = 2,
                            RangId = 1,
                            StoelNr = 2,
                            isInvalide = 0
                        },
                        new
                        {
                            StoelId = 3,
                            RangId = 2,
                            StoelNr = 1,
                            isInvalide = 0
                        },
                        new
                        {
                            StoelId = 4,
                            RangId = 2,
                            StoelNr = 2,
                            isInvalide = 0
                        },
                        new
                        {
                            StoelId = 5,
                            RangId = 3,
                            StoelNr = 1,
                            isInvalide = 0
                        },
                        new
                        {
                            StoelId = 7,
                            RangId = 4,
                            StoelNr = 1,
                            isInvalide = 1
                        },
                        new
                        {
                            StoelId = 8,
                            RangId = 4,
                            StoelNr = 2,
                            isInvalide = 0
                        },
                        new
                        {
                            StoelId = 9,
                            RangId = 5,
                            StoelNr = 1,
                            isInvalide = 0
                        });
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Voorstelling", b =>
                {
                    b.Property<int>("VoorstellingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Prijs")
                        .HasColumnType("REAL");

                    b.Property<string>("Tijd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZaalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoorstellingId");

                    b.HasIndex("GroepId");

                    b.HasIndex("ZaalId");

                    b.ToTable("Voorstelling");

                    b.HasData(
                        new
                        {
                            VoorstellingId = 1,
                            Datum = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "miauw",
                            Genre = "Dans",
                            ImageId = 0,
                            Prijs = 15.0,
                            Tijd = "12:12",
                            Title = "kat",
                            ZaalId = 1
                        },
                        new
                        {
                            VoorstellingId = 2,
                            Datum = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "woef",
                            Genre = "Dans",
                            ImageId = 0,
                            Prijs = 15.0,
                            Tijd = "12:12",
                            Title = "hond",
                            ZaalId = 1
                        },
                        new
                        {
                            VoorstellingId = 3,
                            Datum = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "growl",
                            Genre = "Dans",
                            ImageId = 0,
                            Prijs = 15.0,
                            Tijd = "12:12",
                            Title = "luipaard",
                            ZaalId = 2
                        });
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Zaal", b =>
                {
                    b.Property<int>("ZaalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ZaalId");

                    b.ToTable("Zaal");

                    b.HasData(
                        new
                        {
                            ZaalId = 1,
                            Title = "Zaal1"
                        },
                        new
                        {
                            ZaalId = 2,
                            Title = "Zaal2"
                        });
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Admin", b =>
                {
                    b.HasBaseType("TheaterLaakAPi.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Artiest", b =>
                {
                    b.HasBaseType("TheaterLaakAPi.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Artiest");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Donateur", b =>
                {
                    b.HasBaseType("TheaterLaakAPi.Models.ApplicationUser");

                    b.Property<double>("Bedrag")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Donateur");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Medewerker", b =>
                {
                    b.HasBaseType("TheaterLaakAPi.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Medewerker");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheaterLaakAPi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.ApplicationUser", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.Groep", null)
                        .WithMany("Artiesten")
                        .HasForeignKey("GroepId");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.ArtiestGroep", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.Groep", "groep")
                        .WithMany()
                        .HasForeignKey("GroepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheaterLaakAPi.Models.ApplicationUser", "Artiest")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artiest");

                    b.Navigation("groep");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Groep", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.Artiest", null)
                        .WithMany("Groepen")
                        .HasForeignKey("ArtiestId");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Rang", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.Zaal", "Zaal")
                        .WithMany("Rangen")
                        .HasForeignKey("ZaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zaal");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Reservering", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Reserveringen")
                        .HasForeignKey("ApplicationUserId1");

                    b.HasOne("TheaterLaakAPi.Models.Stoel", "Stoel")
                        .WithMany("Reserveringen")
                        .HasForeignKey("StoelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheaterLaakAPi.Models.Voorstelling", "Voorstelling")
                        .WithMany()
                        .HasForeignKey("VoorstellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Stoel");

                    b.Navigation("Voorstelling");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Stoel", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.Rang", "Rang")
                        .WithMany("Stoelen")
                        .HasForeignKey("RangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rang");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Voorstelling", b =>
                {
                    b.HasOne("TheaterLaakAPi.Models.Groep", null)
                        .WithMany("Voorstellingen")
                        .HasForeignKey("GroepId");

                    b.HasOne("TheaterLaakAPi.Models.Zaal", "Zaal")
                        .WithMany("Voorstellingen")
                        .HasForeignKey("ZaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zaal");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.ApplicationUser", b =>
                {
                    b.Navigation("Reserveringen");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Groep", b =>
                {
                    b.Navigation("Artiesten");

                    b.Navigation("Voorstellingen");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Rang", b =>
                {
                    b.Navigation("Stoelen");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Stoel", b =>
                {
                    b.Navigation("Reserveringen");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Zaal", b =>
                {
                    b.Navigation("Rangen");

                    b.Navigation("Voorstellingen");
                });

            modelBuilder.Entity("TheaterLaakAPi.Models.Artiest", b =>
                {
                    b.Navigation("Groepen");
                });
#pragma warning restore 612, 618
        }
    }
}
